# 服务端口号
server:
  port: 80

spring:
  application:
    name: cloud-order-service

# 链路追踪
  zipkin:
    base-url: http://192.168.16.128:9411
  sleuth:
    sampler:
      probability: 1  #采样率值介于 0 到 1 之间，1 则表示全部采集

eureka:
  client:
    #表示是否将自己注册进EurekaServer默认为true。
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true。单节点无所谓，
    #集群必须设置为true才能配合ribbon使用负载均衡
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:7003/eureka
      #defaultZone: http://localhost:7001/eureka # 单机
#      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka # 集群