server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.16.128:1111  #配置Nacos集群地址

management:
  endpoints:
    web:
      exposure:
        include: '*'
