server:
  port: 80

spring:
  application:
    name: consul-consumer-order
  cloud:
    ####consul注册中心地址
    consul:
      host: localhost
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
